//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn tất.
        /// </summary>
        internal static string BUTTON_HoanTat {
            get {
                return ResourceManager.GetString("BUTTON_HoanTat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy lại mất khẩu.
        /// </summary>
        internal static string BUTTON_LayLaiMatKhau {
            get {
                return ResourceManager.GetString("BUTTON_LayLaiMatKhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string BUTTON_LogIn {
            get {
                return ResourceManager.GetString("BUTTON_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        internal static string BUTTON_LogOut {
            get {
                return ResourceManager.GetString("BUTTON_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        internal static string BUTTON_ThanhToan {
            get {
                return ResourceManager.GetString("BUTTON_ThanhToan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm vào giỏ hàng.
        /// </summary>
        internal static string BUTTON_ThemVaoGioHang {
            get {
                return ResourceManager.GetString("BUTTON_ThemVaoGioHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục mua hàng.
        /// </summary>
        internal static string BUTTON_TiepTucMuaHang {
            get {
                return ResourceManager.GetString("BUTTON_TiepTucMuaHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa sản phẩm.
        /// </summary>
        internal static string BUTTON_XoaSanPham {
            get {
                return ResourceManager.GetString("BUTTON_XoaSanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;a href=&quot;napopet.vn&quot; data-cke-saved-href=&quot;napopet.vn&quot;&gt;&lt;img src=&quot;/UserFiles/images/logo3.png&quot; data-cke-saved-src=&quot;/UserFiles/images/logo3.png&quot; alt=&quot;logo Cty&quot; style=&quot;height:60px; width:264px&quot;&gt;&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        internal static string HTML_Logo_Footter {
            get {
                return ResourceManager.GetString("HTML_Logo_Footter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;a href=&quot;napopet.vn&quot; data-cke-saved-href=&quot;napopet.vn&quot;&gt;&lt;img src=&quot;/UserFiles/images/logo3.png&quot; data-cke-saved-src=&quot;/UserFiles/images/logo3.png&quot; style=&quot;width: 264px; height: 60px;&quot; alt=&quot;logo cty&quot;&gt;&lt;/a&gt;&lt;br&gt;&lt;/p&gt;.
        /// </summary>
        internal static string HTML_Logo_Header {
            get {
                return ResourceManager.GetString("HTML_Logo_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 69 BÀ HUYỆN THANH QUAN, P6, QUẬN 3, HỒ CHÍ MINH.
        /// </summary>
        internal static string INFO_DiaChiCty {
            get {
                return ResourceManager.GetString("INFO_DiaChiCty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0935523169 - 0986899332.
        /// </summary>
        internal static string INFO_DienThoai {
            get {
                return ResourceManager.GetString("INFO_DienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@napopet.com.
        /// </summary>
        internal static string INFO_EmailCty {
            get {
                return ResourceManager.GetString("INFO_EmailCty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gọi ngay: 0986 899 332.
        /// </summary>
        internal static string INFO_HotLine {
            get {
                return ResourceManager.GetString("INFO_HotLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có thể quan tâm.
        /// </summary>
        internal static string Title_BanCoTheQuanTam {
            get {
                return ResourceManager.GetString("Title_BanCoTheQuanTam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã quyên mật khẩu.
        /// </summary>
        internal static string Title_BanDaQuyenMatKhau {
            get {
                return ResourceManager.GetString("Title_BanDaQuyenMatKhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn hãy nhập email để lấy lại mật khẩu.
        /// </summary>
        internal static string Title_BanHayNhapEmailDeLaylai {
            get {
                return ResourceManager.GetString("Title_BanHayNhapEmailDeLaylai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký tài khoản.
        /// </summary>
        internal static string Title_DangKyTaiKhoan {
            get {
                return ResourceManager.GetString("Title_DangKyTaiKhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dạng lưới.
        /// </summary>
        internal static string Title_DangLuoi {
            get {
                return ResourceManager.GetString("Title_DangLuoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục sản phẩm.
        /// </summary>
        internal static string Title_DanhMucSanPham {
            get {
                return ResourceManager.GetString("Title_DanhMucSanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách.
        /// </summary>
        internal static string Title_DanhSach {
            get {
                return ResourceManager.GetString("Title_DanhSach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính.
        /// </summary>
        internal static string Title_DonViTinh {
            get {
                return ResourceManager.GetString("Title_DonViTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Title_Email {
            get {
                return ResourceManager.GetString("Title_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá tiền.
        /// </summary>
        internal static string Title_GiaTien {
            get {
                return ResourceManager.GetString("Title_GiaTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng.
        /// </summary>
        internal static string Title_GioHang {
            get {
                return ResourceManager.GetString("Title_GioHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng bạn có.
        /// </summary>
        internal static string Title_GioHangBanCo {
            get {
                return ResourceManager.GetString("Title_GioHangBanCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển khoản.
        /// </summary>
        internal static string Title_GioHang_ChuyenKhoan {
            get {
                return ResourceManager.GetString("Title_GioHang_ChuyenKhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng.
        /// </summary>
        internal static string Title_GioHang_DatHang {
            get {
                return ResourceManager.GetString("Title_GioHang_DatHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng thành công.
        /// </summary>
        internal static string Title_GioHang_DatHangThanhCong {
            get {
                return ResourceManager.GetString("Title_GioHang_DatHangThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ giao hàng.
        /// </summary>
        internal static string Title_GioHang_DiaChiGiaoHang {
            get {
                return ResourceManager.GetString("Title_GioHang_DiaChiGiaoHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Title_GioHang_Email {
            get {
                return ResourceManager.GetString("Title_GioHang_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        internal static string Title_GioHang_GhiChu {
            get {
                return ResourceManager.GetString("Title_GioHang_GhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị đơn hàng.
        /// </summary>
        internal static string Title_GioHang_GiaTriDonHang {
            get {
                return ResourceManager.GetString("Title_GioHang_GiaTriDonHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức thanh toán.
        /// </summary>
        internal static string Title_GioHang_HinhThucThanhToan {
            get {
                return ResourceManager.GetString("Title_GioHang_HinhThucThanhToan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn tất.
        /// </summary>
        internal static string Title_GioHang_HoanTat {
            get {
                return ResourceManager.GetString("Title_GioHang_HoanTat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giao.
        /// </summary>
        internal static string Title_GioHang_NgayGiao {
            get {
                return ResourceManager.GetString("Title_GioHang_NgayGiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người nhận.
        /// </summary>
        internal static string Title_GioHang_NguoiNhan {
            get {
                return ResourceManager.GetString("Title_GioHang_NguoiNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận tiền khi giao.
        /// </summary>
        internal static string Title_GioHang_NhanTienKhiGiao {
            get {
                return ResourceManager.GetString("Title_GioHang_NhanTienKhiGiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại giao.
        /// </summary>
        internal static string Title_GioHang_SoDienThoai {
            get {
                return ResourceManager.GetString("Title_GioHang_SoDienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Về trang chủ.
        /// </summary>
        internal static string Title_GioHang_VeTrangChu {
            get {
                return ResourceManager.GetString("Title_GioHang_VeTrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        internal static string Title_HinhAnh {
            get {
                return ResourceManager.GetString("Title_HinhAnh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ đệm.
        /// </summary>
        internal static string Title_HoDem {
            get {
                return ResourceManager.GetString("Title_HoDem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAPO &apos;S PET SHOP.
        /// </summary>
        internal static string Title_HomeDefault {
            get {
                return ResourceManager.GetString("Title_HomeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        internal static string Title_HoTen {
            get {
                return ResourceManager.GetString("Title_HoTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có sản phẩm nào.
        /// </summary>
        internal static string Title_KhongCoSanPhamNao {
            get {
                return ResourceManager.GetString("Title_KhongCoSanPhamNao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên lạc.
        /// </summary>
        internal static string Title_LienLac {
            get {
                return ResourceManager.GetString("Title_LienLac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mặt hàng trong giỏ.
        /// </summary>
        internal static string Title_MaHangTrongGio {
            get {
                return ResourceManager.GetString("Title_MaHangTrongGio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm.
        /// </summary>
        internal static string Title_MaSanPham {
            get {
                return ResourceManager.GetString("Title_MaSanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string Title_MatKhau {
            get {
                return ResourceManager.GetString("Title_MatKhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màu.
        /// </summary>
        internal static string Title_Mau {
            get {
                return ResourceManager.GetString("Title_Mau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        internal static string Title_NgaySinh {
            get {
                return ResourceManager.GetString("Title_NgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu.
        /// </summary>
        internal static string Title_NhapLaiMatKhau {
            get {
                return ResourceManager.GetString("Title_NhapLaiMatKhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập từ khóa tìm kiếm.
        /// </summary>
        internal static string Title_NhapTuKhoaTimKiem {
            get {
                return ResourceManager.GetString("Title_NhapTuKhoaTimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        internal static string Title_SanPham {
            get {
                return ResourceManager.GetString("Title_SanPham", resourceCulture);
            }
        }
    }
}
