//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyvanban151116.tvchuong.library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileVanBan
    {
        public long FileID { get; set; }
        public int VanBanID { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string ClientFileName { get; set; }
        public string ServerFileName { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public string MapPath { get; set; }
        public Nullable<int> PageNumber { get; set; }
        public Nullable<int> DownloadCount { get; set; }
    
        public virtual VanBan VanBan { get; set; }
    }
}
