//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyvanban151116.tvchuong.library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VanBan()
        {
            this.FileVanBans = new HashSet<FileVanBan>();
        }
    
        public int VanBanID { get; set; }
        public string TieuDe { get; set; }
        public string TieuDeKhongDau { get; set; }
        public string SoVanBan { get; set; }
        public string TomTatNoiDung { get; set; }
        public string TomTatNoiDungKhongDau { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<bool> IsPublish { get; set; }
        public Nullable<bool> GhimLenDau { get; set; }
        public string Tag { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileVanBan> FileVanBans { get; set; }
    }
}
